version: 2
updates:
  - package-ecosystem: github-actions
    directory: /

    schedule:
      interval: "cron"
      cronjob: "15 1 * * 0"

    open-pull-requests-limit: 1

    groups:
      github-actions:
        patterns:
          - "*"

    commit-message:
      prefix: "[GITHUB-ACTIONS] "

    rebase-strategy: "disabled"

    allow:
      - dependency-type: "all"

  - package-ecosystem: pip
    directory: /

    schedule:
      interval: "cron"
      cronjob: "15 1 * * 0"

    open-pull-requests-limit: 1

    groups:
      pip:
        patterns:
          - "*"

    commit-message:
      prefix: "[PIP] "

    rebase-strategy: "disabled"

    versioning-strategy: increase

    allow:
      - dependency-type: "all"



# NOTE: this file is managed by terraform
