---
version: 1
disable_existing_loggers: false

# Defines log message layout, structure, and text representation
formatters:
  plain:
    format: "%(asctime)s.%(msecs)03d::%(levelname)s::%(funcName)s::%(filename)s:%(lineno)s::%(message)s"
  json:
    format: '{"_t": "%(asctime)s.%(msecs)03d", "_l": "%(levelname)s", "_f": "%(funcName)s", "_m": "%(filename)s:%(lineno)s", "_d": "%(message)s"}'
  lambda_json:
    format: '{"_l": "%(levelname)s", "_m": "%(filename)s:%(lineno)s", "_d": "%(message)s"}'

# Determine the destination of log messages
# - destination be stdout, files
# - set minimum severity level to process a message (overrides loggers: level)
# - use a specific formatter
# - log level: NOTSET(0) DEBUG (10), INFO (20), WARNING (30), ERROR (40), CRITICAL (50)
handlers:
  # use case: docker
  console_structured:
    class: logging.StreamHandler
    formatter: json
    level: DEBUG

  # use case: lambda
  console_lambda:
    class: logging.StreamHandler
    formatter: lambda_json
    level: DEBUG

  # use case: local
  console_local:
    class: logging.StreamHandler
    formatter: plain
    level: DEBUG

  # use case: local
  file:
    class: logging.handlers.RotatingFileHandler
    filename: app.log
    formatter: json
    level: DEBUG
    maxBytes: 10485760 # 10MB file limit
    backupCount: 5

# Capture data from app code
# - set minimum severity level to process a message in logging
# - route to handlers
# - decide to pass message to its parent or not
loggers:
  # Library (no handlers)
  library:
    level: DEBUG
    handlers: []
    propagate: true

  # Application loggers
  local:
    level: DEBUG
    handlers: [console_local, file]
    propagate: false

  default:
    level: DEBUG
    handlers: [console_local]
    propagate: false

  docker:
    level: DEBUG
    handlers: [console_structured]
    propagate: false

  lambda:
    level: DEBUG
    handlers: [console_lambda]
    propagate: false
